### ISSUE TITLE
"plugins": ["katex"] instead of plugins: ["katex"]

### ISSUE THREAD

**Issue by beyondpie** [GitbookIO/plugin-katex#12]
Hi,
when I install katex, I found it reported error if I type plugins: ["katex"].
But, 
```
"plugins": ["katex"]
```
is fine for me.

**Comment by cimi** [comment]
This is because [JSON needs to have field names quoted](https://stackoverflow.com/questions/949449/json-spec-does-the-key-have-to-be-surrounded-with-quotes) (like all strings in JavaScript).  This is different from how JavaScript object literals work - there you don't need to treat field names as strings.

It's not a problem with gitbook or the plugin, it's just the way the format works.

**Comment by AaronO** [comment]
@cimi Is correct.
